# Generated by Django 3.2.16 on 2022-12-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0005_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonstaff',
            name='designation',
            field=models.CharField(choices=[('counsellor', 'counsellor'), ('principal', 'principal'), ('vice principal', 'vice principal'), ('office', 'office'), ('reciptionist', 'reciptionist')], max_length=50, null=True),
        ),
    ]
