# Generated by Django 3.2.16 on 2022-12-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_rename_teachers_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
    ]
