# Generated by Django 3.2.16 on 2022-12-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20221226_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
    ]
