# Generated by Django 3.2.16 on 2022-12-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0014_auto_20221226_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
