# Generated by Django 3.2.16 on 2022-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20221227_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonstaff',
            name='designation',
            field=models.CharField(choices=[('counsellor', 'counsellor'), ('principal', 'principal'), ('vice principal', 'vice principal'), ('office', 'office'), ('reciptionist', 'reciptionist')], max_length=20, null=True),
        ),
    ]
