# Generated by Django 3.2.16 on 2022-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_alter_nonstaff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
