# Generated by Django 3.2.16 on 2022-12-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_alter_school_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstaff',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
