# Generated by Django 3.2.16 on 2022-12-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20221230_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img1.jpg', null=True, upload_to=''),
        ),
    ]
