# Generated by Django 3.2.16 on 2022-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_alter_school_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remarks',
            old_name='remarks_on',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='user',
        ),
        migrations.AddField(
            model_name='remarks',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img1.jpg', null=True, upload_to=''),
        ),
    ]
