# Generated by Django 3.2.16 on 2022-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_auto_20221230_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='student',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
