# Generated by Django 3.2.16 on 2022-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_alter_remark_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
